# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'control_panel.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDial, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QSlider,
    QStatusBar, QTabWidget, QTableView, QToolButton,
    QWidget)

class Ui_ControlPanel(object):
    def setupUi(self, ControlPanel):
        if not ControlPanel.objectName():
            ControlPanel.setObjectName(u"ControlPanel")
        ControlPanel.resize(295, 710)
        self.central_widget = QWidget(ControlPanel)
        self.central_widget.setObjectName(u"central_widget")
        self.button_create_connection = QPushButton(self.central_widget)
        self.button_create_connection.setObjectName(u"button_create_connection")
        self.button_create_connection.setGeometry(QRect(20, 50, 121, 24))
        self.label_connection_status = QLabel(self.central_widget)
        self.label_connection_status.setObjectName(u"label_connection_status")
        self.label_connection_status.setGeometry(QRect(20, 80, 251, 16))
        self.button_scan_disconnect = QPushButton(self.central_widget)
        self.button_scan_disconnect.setObjectName(u"button_scan_disconnect")
        self.button_scan_disconnect.setGeometry(QRect(150, 50, 121, 24))
        self.tab_widget_controller = QTabWidget(self.central_widget)
        self.tab_widget_controller.setObjectName(u"tab_widget_controller")
        self.tab_widget_controller.setGeometry(QRect(20, 120, 251, 531))
        self.tab_speed_controller = QWidget()
        self.tab_speed_controller.setObjectName(u"tab_speed_controller")
        self.static_label_current_velocity = QLabel(self.tab_speed_controller)
        self.static_label_current_velocity.setObjectName(u"static_label_current_velocity")
        self.static_label_current_velocity.setGeometry(QRect(10, 10, 101, 16))
        font = QFont()
        font.setUnderline(True)
        self.static_label_current_velocity.setFont(font)
        self.label_current_velocity = QLabel(self.tab_speed_controller)
        self.label_current_velocity.setObjectName(u"label_current_velocity")
        self.label_current_velocity.setGeometry(QRect(10, 30, 91, 31))
        font1 = QFont()
        font1.setPointSize(20)
        self.label_current_velocity.setFont(font1)
        self.static_label_velocity_multiplier = QLabel(self.tab_speed_controller)
        self.static_label_velocity_multiplier.setObjectName(u"static_label_velocity_multiplier")
        self.static_label_velocity_multiplier.setGeometry(QRect(10, 260, 121, 16))
        self.static_label_velocity_multiplier.setFont(font)
        self.button_set_multiplier = QPushButton(self.tab_speed_controller)
        self.button_set_multiplier.setObjectName(u"button_set_multiplier")
        self.button_set_multiplier.setGeometry(QRect(10, 370, 221, 24))
        self.label_slider_multiplier_value = QLabel(self.tab_speed_controller)
        self.label_slider_multiplier_value.setObjectName(u"label_slider_multiplier_value")
        self.label_slider_multiplier_value.setGeometry(QRect(10, 320, 101, 16))
        self.label_slider_multiplier_push_value = QLabel(self.tab_speed_controller)
        self.label_slider_multiplier_push_value.setObjectName(u"label_slider_multiplier_push_value")
        self.label_slider_multiplier_push_value.setGeometry(QRect(10, 340, 111, 16))
        self.static_label_velocity_slider = QLabel(self.tab_speed_controller)
        self.static_label_velocity_slider.setObjectName(u"static_label_velocity_slider")
        self.static_label_velocity_slider.setGeometry(QRect(10, 140, 121, 16))
        self.static_label_velocity_slider.setFont(font)
        self.label_dial_value = QLabel(self.tab_speed_controller)
        self.label_dial_value.setObjectName(u"label_dial_value")
        self.label_dial_value.setGeometry(QRect(140, 170, 91, 16))
        self.radio_button_default_off = QRadioButton(self.tab_speed_controller)
        self.radio_button_default_off.setObjectName(u"radio_button_default_off")
        self.radio_button_default_off.setGeometry(QRect(10, 80, 89, 21))
        self.radio_button_default_off.setChecked(True)
        self.radio_button_default_on = QRadioButton(self.tab_speed_controller)
        self.radio_button_default_on.setObjectName(u"radio_button_default_on")
        self.radio_button_default_on.setGeometry(QRect(10, 100, 89, 20))
        self.radio_button_default_on.setChecked(False)
        self.button_pulse_motor = QPushButton(self.tab_speed_controller)
        self.button_pulse_motor.setObjectName(u"button_pulse_motor")
        self.button_pulse_motor.setGeometry(QRect(140, 80, 91, 41))
        self.slider_velocity_multiplier = QSlider(self.tab_speed_controller)
        self.slider_velocity_multiplier.setObjectName(u"slider_velocity_multiplier")
        self.slider_velocity_multiplier.setGeometry(QRect(10, 290, 221, 18))
        self.slider_velocity_multiplier.setMinimum(1)
        self.slider_velocity_multiplier.setMaximum(100)
        self.slider_velocity_multiplier.setOrientation(Qt.Horizontal)
        self.static_label_pulse_value = QLabel(self.tab_speed_controller)
        self.static_label_pulse_value.setObjectName(u"static_label_pulse_value")
        self.static_label_pulse_value.setGeometry(QRect(140, 10, 101, 16))
        self.static_label_pulse_value.setFont(font)
        self.label_pulse_value = QLabel(self.tab_speed_controller)
        self.label_pulse_value.setObjectName(u"label_pulse_value")
        self.label_pulse_value.setGeometry(QRect(140, 30, 91, 31))
        self.label_pulse_value.setFont(font1)
        self.dial_velocity = QDial(self.tab_speed_controller)
        self.dial_velocity.setObjectName(u"dial_velocity")
        self.dial_velocity.setGeometry(QRect(20, 160, 81, 81))
        self.dial_velocity.setMinimum(-100)
        self.dial_velocity.setMaximum(100)
        self.static_label_dial_range = QLabel(self.tab_speed_controller)
        self.static_label_dial_range.setObjectName(u"static_label_dial_range")
        self.static_label_dial_range.setGeometry(QRect(140, 190, 101, 16))
        self.tab_widget_controller.addTab(self.tab_speed_controller, "")
        self.tab_pid_control = QWidget()
        self.tab_pid_control.setObjectName(u"tab_pid_control")
        self.static_label_manual_pid_control = QLabel(self.tab_pid_control)
        self.static_label_manual_pid_control.setObjectName(u"static_label_manual_pid_control")
        self.static_label_manual_pid_control.setGeometry(QRect(10, 80, 121, 16))
        self.static_label_manual_pid_control.setFont(font)
        self.lineedit_manual_load = QLineEdit(self.tab_pid_control)
        self.lineedit_manual_load.setObjectName(u"lineedit_manual_load")
        self.lineedit_manual_load.setGeometry(QRect(10, 100, 221, 21))
        self.static_label_current_target_load = QLabel(self.tab_pid_control)
        self.static_label_current_target_load.setObjectName(u"static_label_current_target_load")
        self.static_label_current_target_load.setGeometry(QRect(10, 10, 121, 16))
        self.static_label_current_target_load.setFont(font)
        self.label_current_target_load = QLabel(self.tab_pid_control)
        self.label_current_target_load.setObjectName(u"label_current_target_load")
        self.label_current_target_load.setGeometry(QRect(10, 30, 201, 31))
        self.label_current_target_load.setFont(font1)
        self.button_send_target_load = QPushButton(self.tab_pid_control)
        self.button_send_target_load.setObjectName(u"button_send_target_load")
        self.button_send_target_load.setGeometry(QRect(10, 130, 221, 24))
        self.static_label_automatic_pid_control = QLabel(self.tab_pid_control)
        self.static_label_automatic_pid_control.setObjectName(u"static_label_automatic_pid_control")
        self.static_label_automatic_pid_control.setGeometry(QRect(10, 180, 201, 16))
        self.static_label_automatic_pid_control.setFont(font)
        self.button_import_program = QPushButton(self.tab_pid_control)
        self.button_import_program.setObjectName(u"button_import_program")
        self.button_import_program.setGeometry(QRect(140, 200, 91, 24))
        self.button_execute_program = QPushButton(self.tab_pid_control)
        self.button_execute_program.setObjectName(u"button_execute_program")
        self.button_execute_program.setGeometry(QRect(140, 230, 91, 24))
        self.button_terminate_program = QPushButton(self.tab_pid_control)
        self.button_terminate_program.setObjectName(u"button_terminate_program")
        self.button_terminate_program.setGeometry(QRect(140, 320, 91, 24))
        self.static_label_program_status = QLabel(self.tab_pid_control)
        self.static_label_program_status.setObjectName(u"static_label_program_status")
        self.static_label_program_status.setGeometry(QRect(140, 380, 91, 16))
        self.label_program_status = QLabel(self.tab_pid_control)
        self.label_program_status.setObjectName(u"label_program_status")
        self.label_program_status.setGeometry(QRect(140, 400, 91, 16))
        self.button_clear_program = QPushButton(self.tab_pid_control)
        self.button_clear_program.setObjectName(u"button_clear_program")
        self.button_clear_program.setGeometry(QRect(140, 350, 91, 24))
        self.button_pause_program = QPushButton(self.tab_pid_control)
        self.button_pause_program.setObjectName(u"button_pause_program")
        self.button_pause_program.setGeometry(QRect(140, 260, 91, 24))
        self.button_skip_entry = QPushButton(self.tab_pid_control)
        self.button_skip_entry.setObjectName(u"button_skip_entry")
        self.button_skip_entry.setGeometry(QRect(140, 290, 91, 24))
        self.table_program = QTableView(self.tab_pid_control)
        self.table_program.setObjectName(u"table_program")
        self.table_program.setGeometry(QRect(10, 200, 121, 261))
        self.tool_button_add_row = QToolButton(self.tab_pid_control)
        self.tool_button_add_row.setObjectName(u"tool_button_add_row")
        self.tool_button_add_row.setGeometry(QRect(80, 470, 51, 22))
        self.tool_button_delete_row = QToolButton(self.tab_pid_control)
        self.tool_button_delete_row.setObjectName(u"tool_button_delete_row")
        self.tool_button_delete_row.setGeometry(QRect(10, 470, 51, 22))
        self.tab_widget_controller.addTab(self.tab_pid_control, "")
        self.combo_box_USB_connection = QComboBox(self.central_widget)
        self.combo_box_USB_connection.setObjectName(u"combo_box_USB_connection")
        self.combo_box_USB_connection.setGeometry(QRect(20, 20, 251, 22))
        ControlPanel.setCentralWidget(self.central_widget)
        self.statusbar = QStatusBar(ControlPanel)
        self.statusbar.setObjectName(u"statusbar")
        ControlPanel.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(ControlPanel)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 295, 22))
        ControlPanel.setMenuBar(self.menubar)

        self.retranslateUi(ControlPanel)

        self.tab_widget_controller.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(ControlPanel)
    # setupUi

    def retranslateUi(self, ControlPanel):
        ControlPanel.setWindowTitle(QCoreApplication.translate("ControlPanel", u"Control Panel", None))
        self.button_create_connection.setText(QCoreApplication.translate("ControlPanel", u"Create connection", None))
        self.label_connection_status.setText(QCoreApplication.translate("ControlPanel", u"Status: no connection", None))
        self.button_scan_disconnect.setText(QCoreApplication.translate("ControlPanel", u"Scan", None))
        self.static_label_current_velocity.setText(QCoreApplication.translate("ControlPanel", u"Current Velocity:", None))
        self.label_current_velocity.setText(QCoreApplication.translate("ControlPanel", u"0", None))
        self.static_label_velocity_multiplier.setText(QCoreApplication.translate("ControlPanel", u"Velocity Multiplier:", None))
        self.button_set_multiplier.setText(QCoreApplication.translate("ControlPanel", u"Set multiplier", None))
        self.label_slider_multiplier_value.setText(QCoreApplication.translate("ControlPanel", u"Slider value: 1", None))
        self.label_slider_multiplier_push_value.setText(QCoreApplication.translate("ControlPanel", u"Pushed value: 50", None))
        self.static_label_velocity_slider.setText(QCoreApplication.translate("ControlPanel", u"Velocity Dial:", None))
        self.label_dial_value.setText(QCoreApplication.translate("ControlPanel", u"Dial value: 0", None))
        self.radio_button_default_off.setText(QCoreApplication.translate("ControlPanel", u"Default off", None))
        self.radio_button_default_on.setText(QCoreApplication.translate("ControlPanel", u"Default on", None))
        self.button_pulse_motor.setText(QCoreApplication.translate("ControlPanel", u"Pulse on\n"
"(hold)", None))
        self.static_label_pulse_value.setText(QCoreApplication.translate("ControlPanel", u"Pulse Value:", None))
        self.label_pulse_value.setText(QCoreApplication.translate("ControlPanel", u"0", None))
        self.static_label_dial_range.setText(QCoreApplication.translate("ControlPanel", u"Range: [-100, 100]", None))
        self.tab_widget_controller.setTabText(self.tab_widget_controller.indexOf(self.tab_speed_controller), QCoreApplication.translate("ControlPanel", u"Speed Controller", None))
        self.static_label_manual_pid_control.setText(QCoreApplication.translate("ControlPanel", u"Manual PID Control:", None))
        self.lineedit_manual_load.setPlaceholderText(QCoreApplication.translate("ControlPanel", u"Enter target load in lbs", None))
        self.static_label_current_target_load.setText(QCoreApplication.translate("ControlPanel", u"Current Target Load:", None))
        self.label_current_target_load.setText(QCoreApplication.translate("ControlPanel", u"0 lbs", None))
        self.button_send_target_load.setText(QCoreApplication.translate("ControlPanel", u"Send target load", None))
        self.static_label_automatic_pid_control.setText(QCoreApplication.translate("ControlPanel", u"Automatic PID Control:", None))
        self.button_import_program.setText(QCoreApplication.translate("ControlPanel", u"Import", None))
        self.button_execute_program.setText(QCoreApplication.translate("ControlPanel", u"Execute", None))
        self.button_terminate_program.setText(QCoreApplication.translate("ControlPanel", u"Terminate", None))
        self.static_label_program_status.setText(QCoreApplication.translate("ControlPanel", u"Program Status:", None))
        self.label_program_status.setText(QCoreApplication.translate("ControlPanel", u"Idle", None))
        self.button_clear_program.setText(QCoreApplication.translate("ControlPanel", u"Clear", None))
        self.button_pause_program.setText(QCoreApplication.translate("ControlPanel", u"Pause", None))
        self.button_skip_entry.setText(QCoreApplication.translate("ControlPanel", u"Skip", None))
        self.tool_button_add_row.setText(QCoreApplication.translate("ControlPanel", u"+", None))
        self.tool_button_delete_row.setText(QCoreApplication.translate("ControlPanel", u"-", None))
        self.tab_widget_controller.setTabText(self.tab_widget_controller.indexOf(self.tab_pid_control), QCoreApplication.translate("ControlPanel", u"PID Control", None))
        self.combo_box_USB_connection.setCurrentText("")
        self.combo_box_USB_connection.setPlaceholderText(QCoreApplication.translate("ControlPanel", u"Select USB port", None))
    # retranslateUi

